# Generated by Django 5.1.3 on 2024-11-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
